version: 0.1
os: linux
files:
  - source: /src/HelloWorld.py
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: deploy/before_install.sh
      timeout: 60
  ApplicationStart:
    - location: deploy/application_start.sh
      timeout: 60
  ValidateService:
    - location: deploy/validate_service.sh
      timeout: 60
