version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python src/HelloWorld.py
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Tests started on `date`
      - echo Running unit tests...
      - python tests/HelloWorld_tst.py
      - echo Tests completed on `date`
artifacts:
  files:
    - src/*
    - tests/*
    - *.yml
    - deploy/*
